"""add_user_admin_fields

Revision ID: 0690f3d7709a
Revises: 0511de72ceb5
Create Date: 2025-09-21 09:05:06.611065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0690f3d7709a'
down_revision: Union[str, Sequence[str], None] = '0511de72ceb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    op.execute("UPDATE users SET is_active = 1 WHERE is_active IS NULL")

    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('role', existing_type=sa.String(), nullable=False)
        batch_op.alter_column('is_active', existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
